### ISSUE TITLE
Not able to load dataset on HF

### ISSUE THREAD

**Issue by meharbhatia** [Babelscape/wikineural#1]
Hello, 

Thank you for sharing this dataset on Hugging Face. I was trying to load the dataset however, it seems to be called an error.
```
from datasets import load_dataset
dataset = load_dataset('Babelscape/wikineural', split="train_fr")

FileNotFoundError: Couldn't find file at https://huggingface.co/datasets/Babelscape/wikineural/resolve/main/wikineural.py
```
Can you please check and fix this accordingly!
Thank you :)

**Comment by sted97** [comment]
Hi @meharbhatia, thanks for your interest!! :)

I'm trying to reproduce the error using your fragment of code, but it properly works on both my local machine, a remote machine, and on Google Colab. Are you maybe in a Docker environment?? Maybe you have wrong/old dependencies and it is not able to load the dataset (because it was recently uploaded to HF).

Can you try to create a new conda environment with the latest version of the datasets library??

Hope this helps! :)

Best,
Simone Tedeschi

**Comment by meharbhatia** [comment]
Oh yes.
I made a new environment and then I was able to. Sorry for the inconvenience.
Have a good day :)

**Comment by sted97** [comment]
No worries!! Glad you solved :D

Good day to you too! :)
