### ISSUE TITLE
strange split of NE during recognition

### ISSUE THREAD

**Issue by stefanoscotta** [Babelscape/wikineural#5]
Hi,
I am facing an issue with the model hosted on  [HF](https://huggingface.co/Babelscape/wikineural-multilingual-ner), at least when used with italian texts .
Trying to extract the NE from some text, sometimes (quite often for longer texts) it splits some of the NE recognized in a strange way. 

Below an example of that with the text:
_La scossa è stata avvertita dalla popolazione in tutta la Valdelsa: la gente si è riversata in strada ma al momento, si spiega dalla Protezione civile della Provincia di Siena, non vengono segnalati danni. La scossa è stata avvertita anche nella città del Palio._

the output is 
[{'entity_group': 'LOC',
  'score': 0.99088746,
  'word': 'Valdelsa',
  'start': 58,
  'end': 66},
 **{'entity_group': 'LOC',
  'score': 0.27102342,
  'word': 'Pro',
  'start': 133,
  'end': 136},
 {'entity_group': 'MISC',
  'score': 0.32059246,
  'word': '##tezione',
  'start': 136,
  'end': 143},**
 {'entity_group': 'LOC',
  'score': 0.82290334,
  'word': 'Provincia di Siena',
  'start': 157,
  'end': 175},
 {'entity_group': 'LOC',
  'score': 0.99727523,
  'word': 'Palio',
  'start': 256,
  'end': 261}]

while it probably whould identify at least "Protezione Civile" as an ORG.

**Comment by sted97** [comment]
Hi Stefano, 

This is due to the splitting of the Transformer's tokenizer. Unfortunately, it can happen that subtokens of the same word are labeled with different tags, and therefore they are displayed as different entities. By removing the "grouped_entities" parameter, we can immediately see that "Pro" is labeled as "B-LOC" while "##tezione" is labeled as "I-MISC", which is an impossible annotation according to the BIO tagging scheme. This issue can be easily solved by adding a CRF layer on top of the Transformer, as we did in the paper.

Anyway, this problem usually appears when the context is not sufficiently informative. For instance, in this case, by just capitalizing "Protezione civile" to "Protezione Civile" the system correctly identifies the span.

Hope this helps,

**Comment by stefanoscotta** [comment]
Yes, I understand, thanks a lot.
